- src/content/configuration/file-format.mdx
- src/content/merge-queue/speculative-checks.mdx
- src/content/workflow/actions/queue.mdx
Change-Id: Iaa925769ae9fccdf76207c8caa0af8b019048805
> docs: fix links

- src/content/workflow/actions/rebase.mdx
Change-Id: I39b4abfc6785935daf6f4b99a031422a07790980
> docs(rebase): fix link

- src/content/getting-started.mdx
Change-Id: I3fad1fe5c32bcf61ec08223c50cf0cf008b6a148
> docs: add link from getting started

- src/content/integrations/graphite.mdx
Change-Id: Id6656aff6c3633215f7fbba9376c56f72d298079
> docs(graphite): add link

- src/content/workflow/actions/merge.mdx
Change-Id: I3692771147a75fda9b181fda07472238666ff7f7
> docs(merge): add list of supported branch protections

- src/content/workflow/actions/merge.mdx
Change-Id: I708c01cdd5d4f56ae0b032b64f9caf42a9075ffe
> docs(merge): add link to refresh

- package-lock.json
- package.json
This is required to build our website on CF Pages
> ci(build): add required @parcel/watcher for CF Pages

- src/content/merge-queue/freeze.mdx
Change-Id: Ie3b20222974747899dfdc1d73c21c7a4b72037ac
> docs(mq): add link in freeze

- .github/workflows/deploy-cf.yaml
- cf-build.sh
- package.json
This allows to track deployment.
> ci: add CF Pages -> Slack notifications

- src/content/workflow/writing-your-first-rule.mdx
Change-Id: I90592b5e32271e4ae394cbcab6a5dc75186182d5
> docs(workflow): add missing link

- src/content/billing.mdx
Change-Id: I497ee19df6d8706cb7554f58ab233222b661d135
> docs(billing): add email link

- src/content/merge-queue/speculative-checks.mdx
Change-Id: I49d5944fd46a06b9af410e546dc0b31ba57d7efc
> docs(queue): add link to spec check settings

- src/content/merge-queue/speculative-checks.mdx
Change-Id: I7ca97f1c69d680b3fffd4d05e3a5a322ca1ff4e9
> docs(mq): fix readibility for spec checks schema

- src/components/Sidebar/NavItems.jsx
add width 100%, flex-start & marginRight auto to have standardized width hover on menu item
> feat: add width 100 on menu items to standardize hover effect width

- src/content/merge-queue/batches.mdx
Change-Id: Ia8fdcc9b6bf3261f1978abb543aeb3241a2a39ac
> docs(mq): add schema in batches docs

- src/components/Sidebar/NavItems.jsx
- src/content/config.tsx
- src/content/index.mdx
Change-Id: Ia36673ade1ec3927719b0accc67bc677f3c71735
> docs: add icon support in navbar for pages too

- redirects.json
Using cloudflare allows to use wildcard. This add some missing redirects
and leverages the wildcard system.
> fix: add more redirects

- src/content/integrations/index.mdx
Change-Id: I0b00636d34028d662217106fc0e264d7dd5b3abb
> chore(integrations): remove unused imports

- src/components/Sidebar/NavItems.jsx
Change-Id: I9c881fff4ee31a64051fc58f41a1bdaa658d73cd
> docs: fix navitem external URL

- src/content/merge-queue/lifecycle.mdx
- src/content/workflow/actions/update.mdx
Change-Id: I32751c19bd0d6297402e33dbe7c638f2803bf4d8
> docs: add missing links

- src/content/integrations/dependabot.mdx
- src/content/integrations/gha.mdx
- src/content/integrations/index.mdx
- src/content/integrations/teamcity.mdx
Change-Id: I9a836c8334e39a745b5ea2d05ccf78dd1a65e45d
> docs: add missing entries in integration index

- src/content/config.tsx
- src/content/index.mdx
Change-Id: Iad346d70db882cfa44b49fa6cdf02079b4744a38
> docs: unify icons between indexes and navbar

- src/content/config.tsx
- src/content/integrations/index.mdx
Change-Id: I2f6f294fe2f222c49a427e9d729ec1a9182dc488
> docs: use icons from Si for Jenkins and GHA

- src/content/config.tsx
Change-Id: I77125a76be639cca1f11205c453bb61801eed200
> docs: add home icon

- src/content/security.mdx
Change-Id: I74b81542fe941c20cd709eda70ee55ba4ba8d480
> docs(security): add bug bounty

- src/content/commands/rebase.mdx
Fixes MRGFY-2008
Change-Id: I3104b9ad58462ba4efd29fced53de15affcf9488
> docs(rebase): document hidden features

- src/content/configuration/file-format.mdx
Change-Id: Idfb6f4b666d56877a6981ed146a75d403f8179ee
> docs(file-format): fix sharing link

- src/content/integrations/index.mdx
Change-Id: Ifd1df7b3f6be0d93dce097960262f16a18397b8c
> docs(integrations): fix Jenkins link

- src/content/workflow/actions/queue.mdx
Change-Id: I57b64609455c160734f99aca60202caf863ca6bd
> docs(mq): fix link to spec checks

- src/content/security.mdx
Change-Id: I5433906bc1debe492b1c822afa2e8f5a79b2c8b4
> docs(security): fix mailto mail

- src/content/workflow/actions/assign.mdx
Change-Id: I60247d29e41b0e157c7d979c127968c25811aa98
> docs(assign): fix link to data type

- src/content/integrations/rush.mdx
Change-Id: Ib01a94e00bbd7b06011e67bbe9a38b1b36f85d1b
> docs(rush): fix wrong relative link

- src/content/workflow/automerge.mdx
Change-Id: I6c6b38f7f9c6b214464e6aa188513987c98e3bf6
> docs(automerge): fix link to config spec

- gatsby-config.mjs
- package-lock.json
- package.json
Change-Id: I84d457356da906e9fa0195c6d62649bf59312373
> docs: add Plausible integration

- src/content/config.tsx
- src/content/images/integrations/circleci/logo.svg
- src/content/integrations/circleci.mdx
- src/content/integrations/index.mdx
Change-Id: I14e9519deb0ce36c8bd0cb450ec381a04c566c00
> docs(integrations): add CircleCI

- src/content/workflow/actions/assign.mdx
Change-Id: I592c483c771ef06b28a982e5168f37b62dac43f6
> docs(assign): fix missing s in url

- .github/workflows/ci.yaml
- .gitignore
- gatsby-config.mjs
- package-lock.json
- package.json
- src/components/SearchEngine/PageDetails.tsx
- src/components/SearchEngine/Results.tsx
- src/components/SearchEngine/SearchBar.tsx
- src/components/SearchEngine/types.ts
Adding advanced search with algolia. It can now search through heading, with better word matching and highlights.
We display the table of contents on the result's details
> feat(search): Use Algolia for advanced search

- gatsby-config.mjs
- package-lock.json
- package.json
- src/content/merge-queue/intro.mdx
- src/main.css
Change-Id: Ib1a6a2c0c411e29724f463f6be3d44caf4a91648
> docs(mq): add explanation video

- src/content/integrations/dependabot.mdx
- src/content/merge-queue/batches.mdx
- src/content/merge-queue/priority.mdx
- src/content/merge-queue/setup.mdx
- src/content/merge-queue/speculative-checks.mdx
Change-Id: I4bb490b5f70e6eef2784fad1b9739b1be982aa8a
> docs: add more videos

- src/content/config.tsx
- src/content/index.mdx
Change-Id: I84fd3211040f57659ad62fa1584999d4580a93ba
> docs: add more icons

- src/content/config.tsx
- src/content/index.mdx
- src/content/workflow/actions/index.mdx
- src/content/workflow/actions/request_reviews.mdx
- src/content/workflow/request-reviews.mdx
Change-Id: Icfad844cd15f0045dd6ea9fe70b5d59181fe7182
> docs: add request reviews use case

- src/content/config.tsx
- src/content/index.mdx
- src/content/workflow/actions/delete_head_branch.mdx
- src/content/workflow/delete-head-branches.mdx
Change-Id: Ie4a76dead57024673895d4a370d0ee8ed0d66167
> docs: add delete head branches example

- src/components/SEO/SEO.tsx
OG attributes should be in `property` not `name`
> fix(seo): Open Graph attributes wrongly defined

- src/components/SEO/SEO.tsx
Adding twitter specific meta tags, which are used to preview links when shared on twitter
> feat(seo): Add twitter specific tags for sharing

- src/content/merge-queue/deploy.mdx
Change-Id: Iebe0163bc34e2c9e3f6669d0e473875da7c66830
> docs(mq): add section on Mergify down in deploy

- src/components/MergeQueueCalculator.tsx
Current code uses the previous set batchSize.
Change-Id: Iba5d044eb84d9721190f9468e1729c7d74fbcb1c
> docs(mq): fix performance computing

- src/content/config.tsx
- src/content/index.mdx
- src/content/merge-queue/two-step.mdx
Fixes MRGFY-2482
Change-Id: I614e4e2be7bdcae6089f62aaef92e1e56db54bc9
> docs(mq): document two-step CI

- src/content/merge-queue/performance.mdx
Change-Id: If40ec68874ad04b74c235c9bbd313fbbf0ecc29b
> docs(mq): add link to two-step from performance

- src/components/ConfigOptions.tsx
Change-Id: Ia8799e42a37b45d4ebf874ca9f10a28577a45348
> docs: fix missing space in list rendering

- src/content/config.tsx
- src/content/index.mdx
- src/content/workflow/actions/dismiss_reviews.mdx
- src/content/workflow/actions/index.mdx
- src/content/workflow/dismiss-reviews.mdx
Change-Id: Ie6156700b838a97f8c7bffec0671913bd7cfa073
> docs(workflow): add dismiss reviews use case

- static/mergify-configuration-openapi.json
> docs: update doc for `update_bot_account` behavior with `update_method: merge`

- src/content/index.mdx
- src/content/security.mdx
Fixes MRGFY-1129
Change-Id: Ia1f89135fec2ad4e196e581e8c9b2f564383972b
> docs: document permissions system in Mergify

- src/content/workflow/actions/github_actions.mdx
- static/mergify-configuration-openapi.json
> refactor(github_actions): allow template for inputs

- src/content/billing.mdx
Change-Id: I70377dda4e605e2eb874d3fb99c4694ceb9c4c82
> docs: small billing adjustment

- src/components/ConfigOptions.tsx
- src/content/configuration/data-types.mdx
- static/mergify-configuration-openapi.json
Change-Id: Id9e00f724de71281d859e8db6efe5551d88411a8
> docs: improve schedule configuration

- src/content/billing.mdx
- static/mergify-count-active-users.py
This provides a script to estimate the number of active users over the
last 30 days.
Change-Id: If1e613a356b4a5f7bda88749549f0d3b4e44f938
> docs(billing): add Python script to count for active users

- .github/workflows/deploy-cf.yaml
Change-Id: I1659d651f9decfbb9d07dcda6048610099c5f4f5
> ci: run deploy workflow on ubuntu-latest

- src/content/workflow/actions/merge.mdx
This was never widely deployed.
Change-Id: Ibcdf6fb7d9c0600e0ebed0d98d851476907e95c2
> docs: remove plan tags usage

- static/mergify-count-active-users.py
Change-Id: I56e503ae1ab702a1b1f7014e42cd87e5101c197b
> fix: print GitHub JSON error in case something wrong happens

- static/mergify-configuration-openapi.json
Fixes MRGFY-2800
Fixes MRGFY-2804
Change-Id: I33bd2820d08125fcf2454ad466db74753b73f637
> docs(action): set merge method to none by default

- src/content/workflow/actions/github_actions.mdx
- static/mergify-configuration-openapi.json
Change-Id: I9dcb0c176db29a6830126523cc73978c222caa88
> docs: fix GHA typo

- static/mergify-configuration-openapi.json
Fixes MRGFY-2826
Change-Id: I61facba3fac39e83f429be6251173c45c174f598
> docs: add new attribute head-repo-full-name

- cf-build.sh
Detectify complain about this.
> chore: remove useless file

- src/content/config.tsx
- src/content/configuration/file-format.mdx
- src/content/index.mdx
- src/content/workflow/delete-head-branches.mdx
- src/content/workflow/index.mdx
Fixes MRGFY-2299
Change-Id: I57b0dab8e632b78506cabe582feefa29f1c9786e
> docs: create general workflow intro

- src/utils/mdxast.tsx
When searching, algolia surround matching terms with `em` tags. But for keys inside JSON that are booleans, the JSON is something like `{"default": <em>true</em>}` which is invalid.
This fix surrounds those highlights with quotes, which will make the JSON valid.
> fix(search): Fix `em` tags in boolean values

- gatsby-config.mjs
I followed https://support.algolia.com/hc/en-us/articles/8947249849873-How-do-I-fix-Content-Security-Policy-CSP-errors-on-my-site-
Fixes MRGFY-2843
> chore(csp): add algolia

- gatsby-config.mjs
> fix: add missing self in connect-src

- src/content/index.mdx
Change-Id: Iac58de849324f4125a81e8320b401ad9ec3227a4
> docs: remove double ending dot

- gatsby-config.mjs
> fix(csp): add plausible.io/youtube.com and inline fonts

- static/mergify-configuration-openapi.json
Change-Id: Ice8d83f354a3d8086c8035302c1986ea3741dbb9
> docs: add missing description for TimestampOrTimestampInterval

- static/mergify-configuration-openapi.json
Change-Id: Iaf2a70e5b583e6c645c0dac3d83820eddb602f71
> docs(post_check): document neutral_conditions

- src/components/ConfigOptions.tsx
- static/mergify-configuration-openapi.json
Change-Id: I6c901b63734a7bd78a5f7681a618bfafa974404d
> docs(config): allow null value for checks_timeout

- static/mergify-configuration-openapi.json
Change-Id: Icd32a5c8a48c9106b2309d22a8627e427025d0e7
> docs(queue): allow null for batch_max_failure_resolution_attempts

- src/components/ConfigOptions.tsx
- src/content/configuration/data-types.mdx
- static/mergify-configuration-openapi.json
Change-Id: Id1fe45dfc9677db0d9fcf095d880b6785433bf6e
> docs: add queue-dequeue-reason

- redirects.json
- src/content/commands/dequeue.mdx
- src/content/commands/index.mdx
- src/content/config.tsx
- src/content/configuration/data-types.mdx
- src/content/merge-queue/lifecycle.mdx
- static/mergify-configuration-openapi.json
Change-Id: I40daa480916c351185413ac1fff4fb29f911c1da
> docs(dequeue): rename from unqueue

- src/content/config.tsx
- src/content/index.mdx
- src/content/workflow/actions/post_check.mdx
- src/content/workflow/automerge.mdx
- src/content/workflow/custom-branch-protections.mdx
Fixes MRGFY-2428
Change-Id: If6491382ad44e15eddb56c4a87eb27f4ec76ec5e
> docs: add custom branch protection examples

- src/content/merge-queue/batches.mdx
Change-Id: Ie94a581d7e9b50bbfcedc762902e1c8144de46b2
> docs(mq): tweak a few things in batch and add timeout setting

- src/content/merge-queue/batches.mdx
This was introduced before the docs actually talk about spec checks
below.
Change-Id: Ia2d3ba00489138c088a7eca97a191cc6a0922523
> docs(mq): move paragraph on spec check below

- src/content/merge-queue/_mergify-merge-queue-labels-copier.mdx
- src/content/merge-queue/batches.mdx
- src/content/merge-queue/speculative-checks.mdx
Fixes MRGFY-2894
Change-Id: I98e1e4f70abb19d4983d627c157709eaffa3e0a2
> docs(mq): explain how to keep labels on draft PRs

- src/content/integrations/rush.mdx
- src/content/merge-queue/partitions.mdx
- static/mergify-configuration-openapi.json
Fixes MRGFY-2953
Change-Id: Iff18b58bbbe9d40153eda9ab370975f6ef512b91
> docs: rename queue-partition-name to partition-name

- static/mergify-configuration-openapi.json
> refactor(doc): add deprecation tag for 'require_branch_protection'

- static/mergify-configuration-openapi.json
Fixes MRGFY-2975
Change-Id: I138d57102b3b17802b55c418eebd09b5e1b80b7a
> docs: upate max value for batch_size and speculative_checks

- src/content/badge.mdx
Change-Id: I51ef2575b27f5f0d3755388e976303e9587a25fd
> docs(badges): add a note on private repositories

- gatsby-config.mjs
This will fix loading of badges
Fixes MRGFY-3003
> fix: allow loading resources from img.shields.io

- src/content/workflow/actions/post_check.mdx
Change-Id: I1db5676543baa8a6593082188843dba5cb04f92d
> docs: fix 404 in post_check

- src/content/merge-queue/multi.mdx
- src/content/merge-queue/priority.mdx
Change-Id: I84faa954e82a75a6a5105bd2bef7c614db61ef9d
> docs(mq): add video for multi and priority

- static/mergify-configuration-openapi.json
Change-Id: I7e971e93a1eacda2cb077d49eb46346daac65645
> docs: add `queue-name` attribute

- .github/workflows/ci-docs.yaml
The job need write permissions to create the branch
> ci: fix preview job permissions

- public/sw.js
This readd the service worker file add by Gatsby.
But replace the code to unregister it.
> fix: readd the Gatsby service worker

- public/mergify-configuration-openapi.json
Change-Id: I830427b14c699fe1f99c65afefcdbf66e6d714e6
> docs: add enum for queue_branch_merge_method

- src/content/docs/configuration/conditions.mdx
Change-Id: I8840f1d47c432537bde00d4be7e349fd4283df6d
> docs: fix link to regular expression

- src/components/Tables/PullRequestAttributes.tsx
> fix: sort configuration table by names

- .github/workflows/engine-api-schemas-sync.yml
This will fix the CI : https://github.com/Mergifyio/docs/actions/runs/7496161626/job/20407685362?pr=3156
> ci: change where api-schemas.json is stored

- src/content/docs/configuration/conditions.mdx
- src/content/docs/configuration/data-types.mdx
- src/content/docs/configuration/file-format.mdx
- src/content/docs/workflow/actions/post_check.mdx
Links to an anchor in the same page are broken.
Change-Id: I62c6e28c958d75f976ddc08b5257a4b9642f195b
> docs: fix various 404 on inpage links

- public/mergify-configuration-openapi.json
Following the exposition of this condition, we needed to document it.
Fixes MRGFY-3138
> docs: add documentation for `mergify-configuration-changed`

- public/_headers
> fix(csp): add google fonts server for font-src

- .github/workflows/ci.yaml
- .mergify.yml
- scripts/detect-broken-links.sh
> chore(ci): script to test broken links

- src/content/docs/configuration/data-types.mdx
Change-Id: Ibd403d56b16ad4985b6f5c42da9764a125a7f179
> docs: add missing ago word

- public/mergify-configuration-openapi.json
Change-Id: Ifb11518997e2a4be9f453a906dc9eadd398795a5
> docs: format check names as code

- public/mergify-configuration-openapi.json
Change-Id: Ib32820e8b1491f7594151aaae34099d94cd4cc7f
> docs: add link to "About Status Checks"

- src/content/docs/getting-started.mdx
Change-Id: If86c75f76cf4abee81d6ebce9b6df354dae1d801
> docs(getting-started): add link to billing

- src/content/docs/configuration/data-types.mdx
Fixes MRGFY-3260
Change-Id: Ib5dbbf74d5b81cdd80fb183c7eb7004c9e11b810
> docs(data-type): explain new relative timestamp format

- src/content/docs/workflow/actions/backport.mdx
Change-Id: If8151329c0fb4dcddec5f5c32f4bc800201e929b
> docs(backport): add cherry-pick -x equivalent

- .github/dependabot.yml
- package-lock.json
- package.json
All rollup versions are out of sync.
> fix(deps): set correct rollup version

- src/content/docs/merge-queue/monitoring.mdx
Change-Id: If20f27cf98ea5ef33e784d67ba7397e6e68efefd
> docs(mq): enhance monitoring page

- public/mergify-configuration-openapi.json
- src/content/docs/configuration/file-format.mdx
> docs: add documentation for `description` key of `pull_request_rules`

- public/mergify-configuration-openapi.json
- src/content/docs/configuration/data-types.mdx
Fixes MRGFY-3356
Change-Id: I92bd54b23bb8abe7f00c651d518c7c38742c3f09
> docs: add `none` value to `queue-dequeue-reason`

- .mergify.yml
Cloudflare has changed the check name
Change-Id: I4bbb05c0d4707dd6b8523bfcc1628f4beb285608
> ci: fix Cloudflare pages CI name

- .mergify.yml
Those are not used anymore, don't wait for them
> ci: remove preview checks from conditions

- src/content/docs/security.mdx
Change-Id: I4a8a5312c2d1525dbed7a8cd7d1f888db36cef5e
> docs: fix link to bug bounty

- public/mergify-configuration-openapi.json
We almost never want to allow additional properties on object types.
> fix(schema): Disallow additional properties

- public/mergify-configuration-openapi.json
Fixes MRGFY-3395
Change-Id: I19223f747efbb31d01b71ab292629359dcb38d21
> docs: add {added,modified,deleted}-lines

- public/mergify-configuration-openapi.json
Fixes MRGFY-3394
Change-Id: I890db941bdc76605d5993e0be74171a89dd68045
> docs(config): update default values for copy and backport bodies

- .mergify.yml
> ci: enforce preview job for non-fork PR

- src/content/docs/integrations/teamcity.mdx
Change-Id: I3880615d2db90dd87ced5469c5f9c63bfe1a4940
> docs: add missing part for TeamCity

- src/content/docs/workflow/actions/backport.mdx
- src/content/docs/workflow/actions/copy.mdx
> refactor(actions): describe commits attr in copy and bp

- plugins/remark-algolia.ts
We stringify heading and mdast to extract searchable text for algolia. But the `toString` method used is meant for html AST not mdx. So every mdx-specific nodes (like code nodes) was not included.
Using `toString` from `mdast-util-to-string` does includes those special nodes in the stringify process. But it also stringify the `jsx` nodes (ex: `import File from '...'`) so we need to extract only paragraph nodes to get the excerpt.
This should step-up the search experience a little bit.
> fix(search): Using wrong `toString` method for getting excerpt and heading

- public/mergify-configuration-schema.json
> docs: add `merge_conflict_style` argument for `backport` and `copy` actions

- public/mergify-configuration-schema.json
Fixes MRGFY-3674
Change-Id: I63e455c90eb802bae42f317094504e176191510b
> docs: implement merge protections schema

- public/mergify-count-active-users.py
Change-Id: If796f0b45695d2969c123f318943c310430c8740
> fix: set https in host for GHES

- .mergify.yml
Change-Id: I7aeec8d3a94789da14412df5beafe7a0f81fad6d
> ci(mergify): replace custom rules by merge protections

- src/content/docs/getting-started.mdx
Change-Id: I6bf32ff694b553942795356d80881f1f267e54b2
> docs: update getting started

- src/content/docs/security.mdx
Change-Id: Iefed3c060b08163b183ada2190828ed6a56d93b5
> docs(security): add new merge queue permission

- public/mergify-configuration-schema.json
We started the deprecation process on this attribute
> docs: add deprecated tag to `update_bot_account`

- src/content/docs/workflow/actions/merge.mdx
> docs: complete depends-on doc

- public/mergify-configuration-schema.json
We started the deprecation process for all these attributes
> docs: add deprecated tag for all queue action attributes

- src/content/docs/merge-queue/deploy.mdx
Change-Id: I15a03fa076c03f66858ad85a8587c424d184eee0
> docs(deploy): make sure PR is merged + hint for PR author

- public/mergify-configuration-schema.json
- src/content/docs/configuration/file-format.mdx
- src/content/docs/merge-queue/priority.mdx
Fixes MRGFY-3835
Depends-On: https://github.com/Mergifyio/engine/pull/13474
> docs: modify documentation for `priority_rules` at top-level

- plugins/remark-algolia.ts
- public/mergify-configuration-schema.json
- src/components/Tables/ActionOptionsTable.tsx
- src/components/Tables/OptionsTable.tsx
- src/components/Tables/PullRequestAttributes.tsx
This maps the file format to what Pydantic will generate for us in the
future.
Change-Id: I6e4dc9d79f125d70bc2a14619bbde2eecba87f49
> refactor(config): switch to $defs root key for definition

- package-lock.json
- package.json
- src/components/Tables/ConfigOptions.tsx
- src/components/Tables/OptionsTable.tsx
This replaces custom code to be more generic and make sure the code just
uses $ref as a pointer to the next item to resolve.
Change-Id: I0affcd438e1aba68318b01a37757b59c17c0a89d
> refactor(options): leverage jsonpointer to parse refs

- src/content/docs/configuration/conditions.mdx
- src/content/docs/configuration/data-types.mdx
- src/content/docs/configuration/file-format.mdx
- src/content/docs/configuration/sharing.mdx
Change-Id: Ibfd9a426bba4f8daa9036a19784b501bfc8d5ae6
> refactor(config): add space in conditions format

- src/content/docs/badge.mdx
Change-Id: I968eb49242964f2237dee701b69a2448a9782fdb
> docs(badge): remove useless note

- src/content/docs/integrations/buildkite.mdx
- src/content/docs/integrations/gha.mdx
- src/content/docs/integrations/gitlab.mdx
- src/content/docs/integrations/graphite.mdx
- src/content/docs/integrations/jenkins.mdx
- src/content/docs/integrations/rush.mdx
- src/content/docs/integrations/slack.mdx
- src/content/docs/integrations/teamcity.mdx
Change-Id: Id93d414f45d8f288619051f5f4c5fc7636d80cf5
> docs(integration): update conditions format to include spaces

- src/content/docs/workflow/actions/update.mdx
Change-Id: Iebad520315fb902d8169a8ea20c6f0ca19d6cd4a
> docs: do not talk about rebase in update

- .mergify.yml
Change-Id: I7f479981559c566b6d12b897db464355a420ce26
> ci: allow to ignore broken links

- .mergify.yml
Change-Id: If19c34ec456db1f139c445dda80d2a335692f7fa
> ci: update branch name for automatic update

- src/components/Tables/ConfigOptions.tsx
Change-Id: I9938e42b80f0b26b9064a0bea9fb911870f63332
> docs: remove unused valueType field in option definition

- public/mergify-configuration-schema.json
- src/content/docs/configuration/file-format.mdx
- src/content/docs/merge-queue/speculative-checks.mdx
Fixes MRGFY-4102
Depends-On: https://github.com/Mergifyio/engine/pull/14048
> docs: document `max_parallel_checks` in `merge_queue` section

- src/components/Tables/ConfigOptions.tsx
Change-Id: Idf79c2113631e6788fab74dffc9066e69e0d951c
> refactor(config): use recursive type description

- plugins/remark-algolia.ts
- src/components/Tables/ActionOptionsTable.tsx
- src/components/Tables/ConfigOptions.tsx
- src/components/Tables/OptionsTable.tsx
- src/components/Tables/PullRequestAttributes.tsx
- src/content/docs/commands/restrictions.mdx
- src/content/docs/configuration/data-types.mdx
- src/content/docs/configuration/file-format.mdx
- src/content/docs/merge-queue/partitions.mdx
- src/content/docs/merge-queue/priority.mdx
- src/content/docs/workflow/actions/assign.mdx
- src/content/docs/workflow/actions/backport.mdx
- src/content/docs/workflow/actions/close.mdx
- src/content/docs/workflow/actions/comment.mdx
- src/content/docs/workflow/actions/copy.mdx
- src/content/docs/workflow/actions/delete_head_branch.mdx
- src/content/docs/workflow/actions/dismiss_reviews.mdx
- src/content/docs/workflow/actions/edit.mdx
- src/content/docs/workflow/actions/github_actions.mdx
- src/content/docs/workflow/actions/label.mdx
- src/content/docs/workflow/actions/merge.mdx
- src/content/docs/workflow/actions/post_check.mdx
- src/content/docs/workflow/actions/queue.mdx
- src/content/docs/workflow/actions/rebase.mdx
- src/content/docs/workflow/actions/request_reviews.mdx
- src/content/docs/workflow/actions/review.mdx
- src/content/docs/workflow/actions/squash.mdx
- src/content/docs/workflow/actions/update.mdx
Depends-On: https://github.com/Mergifyio/engine/pull/14088
Depends-On: https://github.com/Mergifyio/engine/pull/14083
Change-Id: I7cddba47065c37b5ffbe9f647b6f839091301c7c
> refactor: switch action and types to new configuration

- public/_headers
This is used by the API documentation.
> fix: add new font provider

- plugins/remark-algolia.ts
- src/components/Tables/ConfigOptions.tsx
- src/components/Tables/PullRequestAttributes.tsx
- src/content/docs/configuration/data-types.mdx
Change-Id: I95f43f42719047a5ca877324df171832b2b0a7ef
> refactor: use new JSON schema for pull request attributes

- src/components/Tables/ConfigOptions.tsx
Fixes MRGFY-4182
Change-Id: Id91138199c098a9f096b87d76e89e1fe26e3435e
Change-Id: I610dfb11bb6918c60a31d863a2c909eebc170bc6
> fix: use new format string for templates

- src/components/Tables/ConfigOptions.tsx
Change-Id: I8454edcd6254e4697792370cd807563ba9dd2c06
> fix: link to date-time and duration formats

- src/components/Footer/footer.ts
Change-Id: Idc26426923c1eedc4408e03930628d68a613ad57
> docs: update links

- src/content/docs/configuration/file-format.mdx
Fixes MRGFY-3954
Change-Id: Idbcabbabfd6629f57396797d947e63cb68d61770
> docs: add missing section on merge_protections format

- public/mergify-count-contributors.py
- src/content/docs/billing.mdx
- src/content/docs/getting-started.mdx
This makes it easier to understand what we charge for.
Change-Id: Icfb46671deaf1e7232271fea5e02388f12e1f9b5
> docs: rename "active users" to contributors

- src/content/docs/merge-queue/setup.mdx
Change-Id: I87c145f92d16258eb63cd660cea3ad6ad936d10b
> docs: add missing link to two-step CI

- src/content/docs/workflow/actions/queue.mdx
Change-Id: I98e0be731d6338e9dbb91db3a0f5b69828fea9b3
> docs(queue): remove deprecated examples

- src/components/Tables/ConfigOptions.tsx
Change-Id: I8e3602f3df98009d685a7780fcbaf2ff757b8514
> docs: add support for const in config schema

- src/content/docs/badge.mdx
Correcting the example badge here, to match the text above
> docs(badge): correct example

- package-lock.json
Fixes https://github.com/Mergifyio/docs/security/dependabot/81
Fixes https://github.com/Mergifyio/docs/security/dependabot/82
> fix: update undici

- package-lock.json
Fixes https://github.com/Mergifyio/docs/security/dependabot/83
Fixes https://github.com/Mergifyio/docs/security/dependabot/80
> fix: update `vite` dependency

- src/components/Tables/OptionsTable.tsx
> fix: allow wraping in option template in table

- src/components/LeftSidebar/NavGroup.astro
- src/components/LeftSidebar/SidebarContent.astro
It's too long to expand it by default.
> refactor: make navbar collapsed by default

- public/_redirects
> fix: add redirect for referenced deleted page

- src/content/docs/workflow/actions/backport.mdx
> docs(backport): example for impersonnating original author

- src/components/Tables/PullRequestAttributes.tsx
> chore: improve layout of conditions page

- src/content/docs/index.mdx
- src/content/docs/security.mdx
- src/content/navItems.tsx
> chore: remove some MQ freeze leftover

- src/content/docs/merge-queue/deploy.mdx
- src/content/docs/merge-queue/parallel-checks.mdx
> docs: mention reset_on_external_merge

- src/content/docs/configuration/file-format.mdx
> docs(mq): add missing section merge_queue

- src/content/docs/configuration/file-format.mdx
- src/content/docs/index.mdx
- src/content/docs/integrations/dependabot.mdx
- src/content/docs/integrations/snyk.mdx
- src/content/docs/merge-queue.mdx
- src/content/docs/merge-queue/lifecycle.mdx
- src/content/docs/merge-queue/pause.mdx
- src/content/docs/merge-queue/rules.mdx
- src/content/docs/merge-queue/setup.mdx
- src/content/docs/security.mdx
We have a single queue with mutliple rules.
Depends-On: #7312
> docs: use MQ singular

- src/content/docs/ci-insights.mdx
- src/content/navItems.tsx
This is not yet activated product side.
> docs: do not show test configuration

- src/content/docs/configuration/file-format.mdx
- src/content/docs/merge-queue/two-step.mdx
> docs: remove allow_inplace_checks mention

- public/mergify-configuration-schema.json
The way to disable speculative checks is implicit.
> feat(MergeQueueModel): add details about speculative checks

- src/content/navItems.tsx
This syncs the sidebar menu with the website
> chore: reorder sidebar menu

- src/content/docs/ci-insights/quarantine.mdx
- src/content/docs/ci-insights/test-frameworks/_gha_mergify_ci_quarantine_setup.mdx
- src/content/docs/ci-insights/test-frameworks/cypress.mdx
- src/content/docs/ci-insights/test-frameworks/golang.mdx
- src/content/docs/ci-insights/test-frameworks/jest.mdx
- src/content/docs/ci-insights/test-frameworks/junit.mdx
- src/content/docs/ci-insights/test-frameworks/minitest.mdx
- src/content/docs/ci-insights/test-frameworks/mstest.mdx
- src/content/docs/ci-insights/test-frameworks/nunit.mdx
- src/content/docs/ci-insights/test-frameworks/pest.mdx
- src/content/docs/ci-insights/test-frameworks/phpunit.mdx
- src/content/docs/ci-insights/test-frameworks/playwright.mdx
- src/content/docs/ci-insights/test-frameworks/rspec.mdx
- src/content/docs/ci-insights/test-frameworks/rust.mdx
- src/content/docs/ci-insights/test-frameworks/testng.mdx
- src/content/docs/ci-insights/test-frameworks/vitest.mdx
- src/content/navItems.tsx
> chore: add documentation for CI Insights Quarantine

- src/content/docs/merge-queue/rules.mdx
- src/content/docs/workflow/actions/queue.mdx
> docs: document autoqueue

- package-lock.json
- package.json
- src/components/HeadCommon.astro
- src/components/PageContent/PageContent.astro
- src/styles/theme.css
> docs: reduce divider top margin

- src/components/Breadcrumbs.astro
> docs: add more bottom space with breadcrumb

- src/styles/index.css
> refactor: clean out empty element

- src/content/docs/security.mdx
Add deployment status and order them alphabetically.
> chore: update repository permissions

- src/pages/api.astro
Hide autosquash from documentation to discourage new usage.
Relates to MRGFY-5882
> docs(Configuration File): hide autosquash
