.github/workflows/docs-upload-gcp-prod.yaml
This can be long: https://github.com/Mergifyio/docs/actions/runs/6274582932/job/17051380264
Fixes INC-90
=> ci: increase timeout of docs-upload-to-gcp-prod

src/content/config.tsx
Some sidebar groups in the `config.tsx` don't have `path` but they still have a page displayed. Just adding the `path` so the sidebar can retrieve which item is active and add its title to the tab title
=> fix: Page title is wrong sometimes

.github/workflows/docs-upload-gcp-prod.yaml
Cloudflare injects some javascripts into static website by default.
We should avoid that to be able to remove unsafe-inline from CSP.
=> fix(cf): ensure Cloudflare doesn't touch the generated page

src/content/merge-queue/setup.mdx
Change-Id: Iea8a6e5eab98d9b137e2129365a87dbf917632a9
=> docs(mq): add missing links in setup

src/content/merge-queue/lifecycle.mdx
Change-Id: I694491ff5f9db0b53b3d6be20448b9c5303e929c
=> docs(mq): add missing links from lifecycle

.github/workflows/docs-upload-gcp-temp.yaml
This replaces GCP authentication from Service Account Key to Workload
Identity Federation
Fixes MRGFY-2694
=> ci: remove usage of secrets.GCP_DOCS_CREDENTIAL_JSON

gatsby-node.mjs
Adding some webpack options that speeds up local builds a little. The most important is the `devtool: "cheap-module-source-map"` that should provide cheaper source map to reduce build time.
=> chore(webpack): Add options to speed up local build

src/components/Sidebar/SidebarNav.tsx
Page title has html comments displayed in production, this is because of how we calculate the title. Now SSR rendering should work correctly
=> fix: Page title is wrongly computed

gatsby-config.mjs
Using `trailingSlash: 'ignore'` will not generates redirect with page ending or not by `/`
For Cloudflare, if no page found, `/foo` == `/foo/` == `/foo/index.html`. And no redirect occurs foo/index.html will be serve for all of them.
We need to be explicit and choose which type of URL we prefer, and Gatsby will generate the appropriate pages/code to redirect all others to our prefered one.
So we need to set `trailingSlash` to `always` or `never`.
I pick `always` like we did for the old documentation.
Fixes MRGFY-2702
=> fix: always add trailing Slash

gatsby-config.mjs, gatsby-node.mjs, package-lock.json, package.json, remark-headings-plugin.mjs, src/@types/mdxast.ts, src/components/ConfigOptions.tsx, src/components/OptionsTable.tsx, src/components/Page.jsx, src/components/PullRequestAttributesTable.jsx, src/components/SearchEngine/PageDetails.tsx, src/components/SearchEngine/Results.tsx, src/components/SearchEngine/SearchBar.tsx, src/components/SearchEngine/types.ts, src/components/mdxComponents.jsx, src/utils/mdxast.tsx
Adding ability to search through page's tables (options, PR attributes, operators, etc). If matched, tables are rendered within the page preview of the search modal.
=> feat(search): Search and display pages tables

gatsby-config.mjs, plugins/algolia-plugin/gatsby-node.js, plugins/algolia-plugin/package.json, src/components/SearchEngine/Results.tsx, src/components/SearchEngine/types.ts
Replacing `gatsby-plugin-algolia` for indexing on algolia by our own plugin. The previous one had issues updating the index: when you update the structure of a record it won't update it because it is based on an id which change only if the page's content changes.
Now we use `saveObjects` from algolia API which does a delete and replace, which makes more sense for us.
=> fix(algolia): Replace `gatsby-plugin-algolia` by own integration

.github/workflows/semantic-pull-request.yaml
This ensures this is retriggered when closing/reopening a PR because GitHub did not run the job.
=> ci: add reopened to semantic check

gatsby-config.mjs
We don't load anything except plausible.io
So hardcode  that in CSP header.
=> fix: stricter CSP

src/content/integrations/_monitoring.mdx
Use absolute path since this is included in different places.
Change-Id: I6c5345722f09ef060f2dd28640c4cd72fe7c4e97
=> docs: fix monitoring links

src/pages/api.tsx, src/pages/dark-mode-override.css
Code blocks in dark mode are not readable. Hacky solution is to extract dark theme CSS file from Prism and to override the API reference styles with it.
=> fix(openapi): Override dark mode colors in api reference

static/mergify-configuration-openapi.json
Our schema expects only one type, not a combination of several types to
be valid.
Change-Id: Id376d9a4acf60e7de8b3d93e010bc9637a1d0daa
=> fix: use oneOf and not anyOf

src/pages/dark-mode-override.css
Wrong usage of CSS selectors which makes overrides also available for light theme.
=> fix(api-reference): Wrong selectors for dark mode overrides

src/pages/api.tsx, src/pages/dark-mode-override.css
Missing parent selector in the code block theme override for api reference. Which was applying it on code blocks everywhere.
=> fix(css): Add missing parent selector in dark mode overrides

src/content/config.tsx, src/content/index.mdx, src/content/merge-queue/batches.mdx, src/content/merge-queue/lifecycle.mdx, src/content/merge-queue/speculative-checks.mdx, src/content/merge-queue/troubleshooting.mdx
This factorize some part of the content and create a new page
troubleshooting. This makes sure the docs are not too verbose and do not
repeat different information in different places.
Change-Id: Ice4085e88260c256ee9007e09921de3179f862ef
=> docs(mq): reorganize a bit spec/batch and add troubleshooting

.github/workflows/engine-api-schemas-sync.yml
The workflow job was failing because openapi-docs-sync is not in the branch protection rules
=> fix(github): fix the sync of API schemas

static/mergify-configuration-openapi.json
JSON schema had issues when validating our own configuration.
- workflow dispatch action takes an array of github actions
- redundant recursive type for RuleCondition
=> fix(schema): Issue with conditions type and workflow dispatch

.github/workflows/ci.yaml, gatsby-config.mjs
This deduplicate the logic of URL everywhere and allow to set them for the
staging site.
=> chore: move out base/site url of gatsby build

src/components/LeftSidebar/NavGroup.astro
There's some missing padding on nav items on sidebar which makes every items on same column.
=> fix(sidebar): Missing padding on nav items in production

cf-build.sh
Cloudflare CF_PAGES_URL is the random assigned domain, not it's alias.
In production, it's not `docs.mergify.com`.
Since docs.mergify.com is the default, this change only set SITE_URL when the deployed branch is a preview one.
=> ci: only set SITE_URL for preview branches

astro.config.ts
Removing `override: true` when populating env variables with `dotenv`. This way env var defined in cloudflare will be taken when building a release.
=> fix: Remove override env var

src/styles/index.css
Left sidebar was on top of the anchor link, without visually hiding it. But the hover was stoped by the sidebar midway on the icon making it disapear and hard to click on.
Also increasing the anchor size to match the title font size, making it a little bit easier to click on.
=> fix: Anchor link is hard to click on

src/content/docs/merge-queue/index.mdx, src/content/docs/workflow/actions/merge.mdx
branch protections can now by bypassed,
so we added a link to the keyword doing allowing
to do so.
=> docs(refactor): update and fix little incoherences

src/content/docs/configuration/conditions.mdx, src/content/docs/configuration/data-types.mdx, src/content/docs/configuration/file-format.mdx, src/content/docs/configuration/sharing.mdx, src/content/docs/merge-queue/batches.mdx, src/content/docs/merge-queue/freeze.mdx, src/content/docs/merge-queue/index.mdx, src/content/docs/merge-queue/lifecycle.mdx, src/content/docs/merge-queue/multi.mdx, src/content/docs/merge-queue/pause.mdx, src/content/docs/merge-queue/performance.mdx, src/content/docs/merge-queue/priority.mdx, src/content/docs/merge-queue/setup.mdx, src/content/docs/merge-queue/troubleshooting.mdx, src/content/docs/merge-queue/two-step.mdx, src/content/docs/workflow/actions/copy.mdx, src/content/docs/workflow/actions/merge.mdx, src/content/docs/workflow/automerge.mdx, src/content/docs/workflow/custom-branch-protections.mdx
Fixing all broken links, those was broken because of the trailing slash added the prod environment which breaks relative links. Solution is to make those not relative anymore.
=> fix: Fix all broken links on docs

src/content/docs/configuration/sharing.mdx
Following the implementation of the YAML anchor extends feature, we needed to add to corresponding documentation.
Fixes MRGFY-3183
=> docs: add documentation for YAML anchor extend feature

public/_headers
They are used by api documentation (scalar)
=> fix: add some missing CSP rules

cf-build.sh
We no longer need this hack since astro is in production.
=> ci: publish the dist directory

public/mergify-configuration-openapi.json, src/components/Tables/ConfigOptions.tsx, src/content/docs/configuration/data-types.mdx
Following the implementation of the new report mode config option for backport and copy actions, we needed to add the corresponding documentation.
Fixes MRGFY-3331
=> docs: add documentation for `report_mode` on copy and backport action

public/mergify-configuration-openapi.json, src/components/Tables/ConfigOptions.tsx
Putting `$id` on every definitions can be hard to handle when we try to reference those. Because `$id` serve as base path when resolving from a schema.
They were used only to get links to some specific types pages, and can be retrieve by using the last segment of the URI.
=> refactor(schema): Remove $id from all definitions

public/mergify-configuration-openapi.json
Adding some missing `additionalProperties: false` on some actions, to disallow properties not listed in this schema. It will provide better feedback and validation.
=> fix(schema): Add missing `additionalProperties: false` on actions

src/components/Tables/OptionsTable.tsx
=> docs: wrap code in `pre` on OptionsTable.mdx

src/content/docs/stacks.mdx
This is the documented upstream command as pip binary may not installed
by default.
=> chore: change the command to install mergify-cli

src/content/docs/integrations/circleci.mdx
When a CI name has a ":," we must quote the whole line.
Otherwise, the YAML parser thinks it's a mapping instead of a string.
Fixes https://github.com/Mergifyio/mergify/issues/5116
=> fix(circleci): add missing quote

.mergify.yml
We don't need to review pull request like #4587 that are just here to sync the openapi types.
=> ci: automerge openapi types sync PR from ci-bot

cf-build.sh
We got some build.log from dependabot while we should care on about
main.
=> ci: fix where build log are posted

src/content/docs/merge-protections/index.mdx
This pull request updates the regex pattern used for merge protection to properly match commit messages with groups.
- File changed: `src/content/docs/merge-protections/index.mdx`
- Modified the regex pattern in the success conditions for merge protection:
- Old: `"title ~= ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))?:"`
- New: `"title ~= ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"`
- Improves the accuracy of commit message validation in merge protection rules
- Ensures that commit messages with scopes (e.g., `feat(api):`) are correctly matched
- Maintains compliance with the Conventional Commits specification (https://www.conventionalcommits.org/en/v1.0.0/)
=> docs: update regex on merge protection to properly match with groups

src/content/docs/configuration/sharing.mdx
=> docs: specify what happens when there are rules with the same name in an extended config

src/content/docs/configuration/sharing.mdx
Fixes MRGFY-4000
Depends-On: https://github.com/Mergifyio/docs/pull/5012
=> docs: add documentation on `commands_restrictions` merging from extended config

src/components/Tables/ConfigOptions.tsx
Fixes MRGFY-4058
Change-Id: Ibc5ba040c15da8efd44f8f6ad64022419dff818d
=> docs: fix missing type description

public/mergify-configuration-schema.json
Fixes MRGFY-4040
Depends-On: https://github.com/Mergifyio/engine/pull/13760
=> docs: document the deprecation of `allow_checks_interruption` in `queue_rules`

package-lock.json
This drops path-to-regex that have critical CVEs.
Fixes https://github.com/Mergifyio/docs/security/dependabot/73
=> fix: upgrade astro

plugins/remark-algolia.ts
When indexing mdx pages to algolia, we retrieve our custom `OptionsTable` and `ActionOptionsTable`, we extract the config schema definitions they render to pass it to algolia in order to provide searching through those tables.
Those tables have changed and takes a `def` props instead of a `name` prop to point to the definition they render, that was breaking things.
=> fix(algolia): wrong key when adding custom table options

.github/workflows/ci.yaml, astro.config.ts, plugins/remark-algolia.ts
We should run the astro build in the CI to catch errors early on the PR. This change make it so the Algolia plugin compiles the MDX but without indexing it, so we will be able to catch further errors before it goes in production.
=> ci: run astro build in the ci

src/content/docs/configuration/conditions.mdx
=> docs: document `not` operator

.mergify.yml
This implements a few changes:
- leverage MP to check for CI
- leverage MP to check for review requirements
=> ci(mergify): upgrade conf to use MP

src/content/docs/merge-queue/priority.mdx
The `priority_rules` inside the `queue_rules` section has already been
fully removed.
=> refactor: remove section about deprecated `priority_rules`

src/content/docs/configuration/sharing.mdx
The example was wrong, the `extends` option take only a repository name.
=> fix(extends): fix the extends example

src/content/docs/ci-insights/cypress.mdx, src/content/docs/ci-insights/golang.mdx, src/content/docs/ci-insights/vitest.mdx
It has been renamed to `report_path`, from `report_paths`
=> chore: fix `report_path` option for `gha-mergify-ci` action

src/content/docs/merge-queue/priority.mdx
Depends-On: https://github.com/Mergifyio/engine/pull/18666
Fixes MRGFY-5075
=> chore: multiple matching priority rules now return first matched rule

src/content/docs/ci-insights/cypress.mdx, src/content/docs/ci-insights/golang.mdx, src/content/docs/ci-insights/pytest.mdx, src/content/docs/ci-insights/vitest.mdx
This makes clear MERGIFY_TOKEN is CI Insights token.
This move the note block just before we need the MERGIFY_TOKEN.
This adds the note block in all others pages.
=> chore: improve documentation of the MERGIFY_TOKEN

src/pages/api.astro
The api reference crash because of the recursive schema of scheduled freeze matching conditions. This change is modifying the api schema on the fly while passing it to the api reference.
=> fix(api): modify MatchingConditionsDict schemas to prevent crashes in api reference

src/pages/api.astro
The api reference loading is flaky.
This is a tentative to fix it by not running the js until the json is
inserted in the DOM
=> fix: ensure json is loaded before loading the js file

src/content/docs/ci-insights.mdx, src/content/navItems.tsx
This reverts commit 580fcc3c246d7d2bcbbe250de79484681c0214f1.
We can enable it now.
=> revert: "docs: do not show test configuration (#7316)"

src/content/docs/ci-insights/setup/github-actions.mdx
This change:
* give a name to examples
* remove npm/gotest as we don't support them yet
=> chore(flaky-tests): fix examples

astro.config.ts, integrations/algolia-update-index.ts, plugins/remark-algolia.ts
This is changing the way we are recording our algolia index.
Instead of updating each page at load, we are collecting them all and replacing the entire index with them at the end.
Relates to MRGFY-5897
=> feat(algolia): Replace index
